subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 2
      leftSlaveOne: 1
      leftSlaveTwo: 3
      rightMain: 7
      rightSlaveOne: 5
      rightSlaveTwo: 6
    constants:
      pigeonId: 3
      pigeonOnTalon: 1
      kP: 5.0
      kI: 0
      kD: 0
      kF: .01548
      iZone: 0
      encPPR: 9752
      maxPos: 1475
      minPos: 915
      invertMotor: 2
      currentFloorCheck: 1.2
      currentEpsilonCheck: .2
      rpmFloorCheck: 4100
      rpmEpsilonCheck: 60
  canifier:
    implemented: false
    constants:
      canId: -1
constants:
  wheelDiameter: 7.5
  trackWidth: 21.75
  maxVel: 50 #inch/s robot max is 223
  maxAccel: 100 #inch/s^2
  sensorPhase: 0
  kLooperDt: .01
  kTrackScrubFactor: 1.0
  kPCMId: 0
  verbose: 0
  pathKs: 0
