$extends: zodiac_base
subsystems:
    climber:
        invertMotor:
            - elevator
    hopper:
        invertMotor:
            - elevator
    shooter:
        falcons:
            shooterMain: 3
            shooterFollower: 2
    turret:
        constants:
            minPos: -3802
            maxPos: -757
    ledmanager:
        implemented: true
        canifier: 18
    camera:
        implemented: true
        canifier: 19
constants:
    wheelDiameter: 6.32 #inches
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
